using System;
using System.IO;
using System.Text;
using GoveKits.Runtime.Util;
using UnityEditor;
using UnityEngine;

namespace GoveKits.Editor
{
    /// <summary>
    /// 项目基础环境初始化工具窗口。
    /// </summary>
    public class ProjectWindow : GoveKitsEditorWindow
    {
        [MenuItem("GoveKits/Project", false, 10)]
        public static void ShowWindow()
        {
            var window = GetWindow<ProjectWindow>("Project 工具");
            window.minSize = new Vector2(450, 250);
            window.Show();
        }

        protected override void OnGoveDrawContent()
        {
            DrawActionSection();
        }

        protected override void DrawHeader()
        {
            GUILayout.Space(10);
            EditorGUILayout.LabelField("项目基础环境初始化工具", EditorStyles.largeLabel);
            GUILayout.Space(5);
            DrawLine();
            GUILayout.Space(10);
        }

        private void DrawActionSection()
        {
            DrawLine();
            GUILayout.Space(10);

            if (GUILayout.Button("初始化项目 .gitignore", GUILayout.Height(30)))
            {
                CreateGitIgnore();
            }

            GUILayout.Space(10);
        }

        private void CreateGitIgnore()
        {
            string fullPath = Path.Combine(GoveKitsPathUtility.ProjectRootPath, ".gitignore");

            if (File.Exists(fullPath))
            {
                bool overwrite = EditorUtility.DisplayDialog(
                    "覆盖确认",
                    $"检测到项目根目录已存在 .gitignore，是否覆盖？\n{fullPath}",
                    "覆盖",
                    "取消");
                if (!overwrite) return;
            }

            try
            {
                File.WriteAllText(fullPath, GitignoreTemplate, Encoding.UTF8);

                ShowNotification(new GUIContent("已成功创建 .gitignore 文件"));
                LogCore.Success("ProjectEditor", $"已创建 .gitignore 文件: {fullPath}");
            }
            catch (Exception e)
            {
                ShowNotification(new GUIContent("创建 .gitignore 失败"));
                LogCore.Error("ProjectEditor", $"创建 .gitignore 失败: {e.Message}");
            }
        }

        private static readonly string GitignoreTemplate = @"# This .gitignore file should be placed at the root of your Unity project directory
#
# Get latest from https://github.com/github/gitignore/blob/main/Unity.gitignore
#
.utmp/
/[Ll]ibrary/
/[Tt]emp/
/[Oo]bj/
/[Bb]uild/
/[Bb]uilds/
/[Ll]ogs/
/[Uu]ser[Ss]ettings/
*.log

# By default unity supports Blender asset imports, *.blend1 blender files do not need to be commited to version control.
*.blend1
*.blend1.meta

# MemoryCaptures can get excessive in size.
# They also could contain extremely sensitive data
/[Mm]emoryCaptures/

# Recordings can get excessive in size
/[Rr]ecordings/

# Autogenerated Jetbrains Rider plugin
/[Aa]ssets/Plugins/Editor/JetBrains*

# Visual Studio cache directory
.vs/

# Gradle cache directory
.gradle/

# Autogenerated VS/MD/Consulo solution and project files
ExportedObj/
.consulo/
*.csproj
*.unityproj
*.sln
*.suo
*.tmp
*.user
*.userprefs
*.pidb
*.booproj
*.svd
*.pdb
*.mdb
*.opendb
*.VC.db

# Unity3D generated meta files
*.pidb.meta
*.pdb.meta
*.mdb.meta

# Unity3D generated file on crash reports
sysinfo.txt

# Builds
*.apk
*.aab
*.unitypackage
*.unitypackage.meta
*.app

# Crashlytics generated file
crashlytics-build.properties

# Packed Addressables
/[Aa]ssets/[Aa]ddressable[Aa]ssets[Dd]ata/*/*.bin*

# Temporary auto-generated Android Assets
/[Aa]ssets/[Ss]treamingAssets/aa.meta
/[Aa]ssets/[Ss]treamingAssets/aa/*

# Visual Scripting auto-generated files
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Flow/UnitOptions.db.meta
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers
/[Aa]ssets/Unity.VisualScripting.Generated/VisualScripting.Core/Property Providers.meta

# HybridCLR generated files
HybridCLRData
";
    }

    /// <summary>
    /// GoveKits 全局 Editor 路径工具类。
    /// </summary>
    internal static class GoveKitsPathUtility
    {
        public static string ProjectRootPath
        {
            get
            {
                DirectoryInfo info = Directory.GetParent(Application.dataPath);
                return info != null ? info.FullName : Application.dataPath;
            }
        }

        public static string ToAbsolutePath(string path)
        {
            if (string.IsNullOrWhiteSpace(path)) return string.Empty;
            if (Path.IsPathRooted(path)) return path;

            string normalized = path.Replace('\\', '/');
            return Path.Combine(ProjectRootPath, normalized);
        }

        public static string ToProjectRelativeOrAbsolute(string absolutePath)
        {
            if (string.IsNullOrWhiteSpace(absolutePath)) return string.Empty;

            string full = Path.GetFullPath(absolutePath).Replace('\\', '/');
            string root = ProjectRootPath.Replace('\\', '/').TrimEnd('/');

            if (full.StartsWith(root + "/", StringComparison.OrdinalIgnoreCase))
            {
                return full.Substring(root.Length + 1);
            }
            return absolutePath;
        }

        public static bool IsSameOrSubPath(string parentPath, string candidatePath)
        {
            if (string.IsNullOrWhiteSpace(parentPath) || string.IsNullOrWhiteSpace(candidatePath)) return false;

            string parent = NormalizeFullPath(parentPath).TrimEnd('/');
            string candidate = NormalizeFullPath(candidatePath).TrimEnd('/');

            return string.Equals(parent, candidate, StringComparison.OrdinalIgnoreCase) ||
                   candidate.StartsWith(parent + "/", StringComparison.OrdinalIgnoreCase);
        }

        public static string NormalizeFullPath(string path)
        {
            return string.IsNullOrWhiteSpace(path) ? string.Empty : Path.GetFullPath(path).Replace('\\', '/');
        }
    }
}
