// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SettingData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SettingData.proto</summary>
public static partial class SettingDataReflection {

  #region Descriptor
  /// <summary>File descriptor for SettingData.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SettingDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFTZXR0aW5nRGF0YS5wcm90bxIHU2V0dGluZyJ2CgxBdWRpb1NldHRpbmcS",
          "FQoNbWFzdGVyX3ZvbHVtZRgBIAEoAhISCgpiZ21fdm9sdW1lGAIgASgCEhIK",
          "CnNmeF92b2x1bWUYAyABKAISEQoJdWlfdm9sdW1lGAQgASgCEhQKDHZvaWNl",
          "X3ZvbHVtZRgFIAEoAiIqChNMb2NhbGl6YXRpb25TZXR0aW5nEhMKC2xhbmd1",
          "YWdlX2lkGAEgASgFQgOqAgBiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AudioSetting), global::AudioSetting.Parser, new[]{ "MasterVolume", "BgmVolume", "SfxVolume", "UiVolume", "VoiceVolume" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::LocalizationSetting), global::LocalizationSetting.Parser, new[]{ "LanguageId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class AudioSetting : pb::IMessage<AudioSetting>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AudioSetting> _parser = new pb::MessageParser<AudioSetting>(() => new AudioSetting());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AudioSetting> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SettingDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioSetting() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioSetting(AudioSetting other) : this() {
    masterVolume_ = other.masterVolume_;
    bgmVolume_ = other.bgmVolume_;
    sfxVolume_ = other.sfxVolume_;
    uiVolume_ = other.uiVolume_;
    voiceVolume_ = other.voiceVolume_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AudioSetting Clone() {
    return new AudioSetting(this);
  }

  /// <summary>Field number for the "master_volume" field.</summary>
  public const int MasterVolumeFieldNumber = 1;
  private float masterVolume_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float MasterVolume {
    get { return masterVolume_; }
    set {
      masterVolume_ = value;
    }
  }

  /// <summary>Field number for the "bgm_volume" field.</summary>
  public const int BgmVolumeFieldNumber = 2;
  private float bgmVolume_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float BgmVolume {
    get { return bgmVolume_; }
    set {
      bgmVolume_ = value;
    }
  }

  /// <summary>Field number for the "sfx_volume" field.</summary>
  public const int SfxVolumeFieldNumber = 3;
  private float sfxVolume_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float SfxVolume {
    get { return sfxVolume_; }
    set {
      sfxVolume_ = value;
    }
  }

  /// <summary>Field number for the "ui_volume" field.</summary>
  public const int UiVolumeFieldNumber = 4;
  private float uiVolume_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float UiVolume {
    get { return uiVolume_; }
    set {
      uiVolume_ = value;
    }
  }

  /// <summary>Field number for the "voice_volume" field.</summary>
  public const int VoiceVolumeFieldNumber = 5;
  private float voiceVolume_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float VoiceVolume {
    get { return voiceVolume_; }
    set {
      voiceVolume_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AudioSetting);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AudioSetting other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MasterVolume, other.MasterVolume)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(BgmVolume, other.BgmVolume)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SfxVolume, other.SfxVolume)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(UiVolume, other.UiVolume)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(VoiceVolume, other.VoiceVolume)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (MasterVolume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MasterVolume);
    if (BgmVolume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(BgmVolume);
    if (SfxVolume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SfxVolume);
    if (UiVolume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(UiVolume);
    if (VoiceVolume != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(VoiceVolume);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MasterVolume != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(MasterVolume);
    }
    if (BgmVolume != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(BgmVolume);
    }
    if (SfxVolume != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(SfxVolume);
    }
    if (UiVolume != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(UiVolume);
    }
    if (VoiceVolume != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(VoiceVolume);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MasterVolume != 0F) {
      output.WriteRawTag(13);
      output.WriteFloat(MasterVolume);
    }
    if (BgmVolume != 0F) {
      output.WriteRawTag(21);
      output.WriteFloat(BgmVolume);
    }
    if (SfxVolume != 0F) {
      output.WriteRawTag(29);
      output.WriteFloat(SfxVolume);
    }
    if (UiVolume != 0F) {
      output.WriteRawTag(37);
      output.WriteFloat(UiVolume);
    }
    if (VoiceVolume != 0F) {
      output.WriteRawTag(45);
      output.WriteFloat(VoiceVolume);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (MasterVolume != 0F) {
      size += 1 + 4;
    }
    if (BgmVolume != 0F) {
      size += 1 + 4;
    }
    if (SfxVolume != 0F) {
      size += 1 + 4;
    }
    if (UiVolume != 0F) {
      size += 1 + 4;
    }
    if (VoiceVolume != 0F) {
      size += 1 + 4;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AudioSetting other) {
    if (other == null) {
      return;
    }
    if (other.MasterVolume != 0F) {
      MasterVolume = other.MasterVolume;
    }
    if (other.BgmVolume != 0F) {
      BgmVolume = other.BgmVolume;
    }
    if (other.SfxVolume != 0F) {
      SfxVolume = other.SfxVolume;
    }
    if (other.UiVolume != 0F) {
      UiVolume = other.UiVolume;
    }
    if (other.VoiceVolume != 0F) {
      VoiceVolume = other.VoiceVolume;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 13: {
          MasterVolume = input.ReadFloat();
          break;
        }
        case 21: {
          BgmVolume = input.ReadFloat();
          break;
        }
        case 29: {
          SfxVolume = input.ReadFloat();
          break;
        }
        case 37: {
          UiVolume = input.ReadFloat();
          break;
        }
        case 45: {
          VoiceVolume = input.ReadFloat();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 13: {
          MasterVolume = input.ReadFloat();
          break;
        }
        case 21: {
          BgmVolume = input.ReadFloat();
          break;
        }
        case 29: {
          SfxVolume = input.ReadFloat();
          break;
        }
        case 37: {
          UiVolume = input.ReadFloat();
          break;
        }
        case 45: {
          VoiceVolume = input.ReadFloat();
          break;
        }
      }
    }
  }
  #endif

}

[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class LocalizationSetting : pb::IMessage<LocalizationSetting>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<LocalizationSetting> _parser = new pb::MessageParser<LocalizationSetting>(() => new LocalizationSetting());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<LocalizationSetting> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SettingDataReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LocalizationSetting() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LocalizationSetting(LocalizationSetting other) : this() {
    languageId_ = other.languageId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public LocalizationSetting Clone() {
    return new LocalizationSetting(this);
  }

  /// <summary>Field number for the "language_id" field.</summary>
  public const int LanguageIdFieldNumber = 1;
  private int languageId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LanguageId {
    get { return languageId_; }
    set {
      languageId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as LocalizationSetting);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(LocalizationSetting other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (LanguageId != other.LanguageId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (LanguageId != 0) hash ^= LanguageId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (LanguageId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(LanguageId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (LanguageId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(LanguageId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (LanguageId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LanguageId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(LocalizationSetting other) {
    if (other == null) {
      return;
    }
    if (other.LanguageId != 0) {
      LanguageId = other.LanguageId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          LanguageId = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
    if ((tag & 7) == 4) {
      // Abort on any end group tag.
      return;
    }
    switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          LanguageId = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
